export const dogsDatabase = [
  {
    id: 1,
    image_link: "https://api-ninjas.com/images/dogs/golden_retriever.jpg",
    good_with_children: 5,
    good_with_other_dogs: 5,
    shedding: 4,
    grooming: 2,
    drooling: 2,
    coat_length: 1,
    good_with_strangers: 5,
    playfulness: 4,
    protectiveness: 3,
    trainability: 5,
    energy: 3,
    barking: 1,
    min_life_expectancy: 10,
    max_life_expectancy: 12,
    max_height_male: 24,
    max_height_female: 24,
    max_weight_male: 75,
    max_weight_female: 65,
    min_height_male: 23,
    min_height_female: 23,
    min_weight_male: 65,
    min_weight_female: 55,
    name: "Golden Retriever",
  },
  {
    id: 2,
    image_link: "https://api-ninjas.com/images/dogs/labrador_retriever.jpg",
    good_with_children: 5,
    good_with_other_dogs: 5,
    shedding: 4,
    grooming: 2,
    drooling: 2,
    coat_length: 1,
    good_with_strangers: 5,
    playfulness: 5,
    protectiveness: 3,
    trainability: 5,
    energy: 5,
    barking: 3,
    min_life_expectancy: 10,
    max_life_expectancy: 12,
    max_height_male: 24.5,
    max_height_female: 24.5,
    max_weight_male: 80,
    max_weight_female: 70,
    min_height_male: 22.5,
    min_height_female: 22.5,
    min_weight_male: 65,
    min_weight_female: 55,
    name: "Labrador Retriever",
  },
  {
    id: 3,
    image_link: "https://api-ninjas.com/images/dogs/siberian_husky.jpg",
    good_with_children: 5,
    good_with_other_dogs: 5,
    shedding: 4,
    grooming: 2,
    drooling: 1,
    coat_length: 1,
    good_with_strangers: 5,
    playfulness: 5,
    protectiveness: 1,
    trainability: 3,
    energy: 5,
    barking: 5,
    min_life_expectancy: 12,
    max_life_expectancy: 14,
    max_height_male: 23.5,
    max_height_female: 23.5,
    max_weight_male: 60,
    max_weight_female: 50,
    min_height_male: 21,
    min_height_female: 21,
    min_weight_male: 45,
    min_weight_female: 35,
    name: "Siberian Husky",
  },
  {
    id: 4,
    image_link: "https://api-ninjas.com/images/dogs/poodle_(standard).jpg",
    good_with_children: 5,
    good_with_other_dogs: 3,
    shedding: 1,
    grooming: 4,
    drooling: 1,
    coat_length: 1,
    good_with_strangers: 5,
    playfulness: 5,
    protectiveness: 5,
    trainability: 5,
    energy: 4,
    barking: 4,
    min_life_expectancy: 10,
    max_life_expectancy: 18,
    max_height_male: 17,
    max_height_female: 17,
    max_weight_male: 70,
    max_weight_female: 50,
    min_height_male: 15,
    min_height_female: 15,
    min_weight_male: 60,
    min_weight_female: 40,
    name: "Poodle",
  },
  {
    id: 5,
    image_link: "https://api-ninjas.com/images/dogs/chow_chow.jpg",
    good_with_children: 3,
    good_with_other_dogs: 2,
    shedding: 3,
    grooming: 3,
    drooling: 3,
    coat_length: 1,
    good_with_strangers: 2,
    playfulness: 3,
    protectiveness: 5,
    trainability: 3,
    energy: 3,
    barking: 1,
    min_life_expectancy: 8,
    max_life_expectancy: 12,
    max_height_male: 20,
    max_height_female: 20,
    max_weight_male: 70,
    max_weight_female: 70,
    min_height_male: 17,
    min_height_female: 17,
    min_weight_male: 45,
    min_weight_female: 45,
    name: "Chow Chow",
  },
  {
    id: 6,
    image_link: "https://api-ninjas.com/images/dogs/german_shepherd_dog.jpg",
    good_with_children: 5,
    good_with_other_dogs: 3,
    shedding: 4,
    grooming: 2,
    drooling: 2,
    coat_length: 1,
    good_with_strangers: 3,
    playfulness: 4,
    protectiveness: 5,
    trainability: 5,
    energy: 5,
    barking: 3,
    min_life_expectancy: 7,
    max_life_expectancy: 10,
    max_height_male: 26,
    max_height_female: 26,
    max_weight_male: 90,
    max_weight_female: 70,
    min_height_male: 24,
    min_height_female: 24,
    min_weight_male: 65,
    min_weight_female: 50,
    name: "German Shepherd",
  },
  {
    id: 7,
    image_link: "https://api-ninjas.com/images/dogs/pomeranian.jpg",
    good_with_children: 3,
    good_with_other_dogs: 3,
    shedding: 2,
    grooming: 3,
    drooling: 1,
    coat_length: 1,
    good_with_strangers: 3,
    playfulness: 3,
    protectiveness: 4,
    trainability: 3,
    energy: 3,
    barking: 4,
    min_life_expectancy: 12,
    max_life_expectancy: 16,
    max_height_male: 7,
    max_height_female: 7,
    max_weight_male: 7,
    max_weight_female: 7,
    min_height_male: 6,
    min_height_female: 6,
    min_weight_male: 3,
    min_weight_female: 3,
    name: "Pomeranian",
  },
  {
    id: 8,
    image_link: "https://api-ninjas.com/images/dogs/american_bulldog.jpg",
    good_with_children: 3,
    good_with_other_dogs: 3,
    shedding: 2,
    coat_length: 1,
    trainability: 4,
    barking: 1,
    min_life_expectancy: 10,
    max_life_expectancy: 12,
    max_height_male: 28,
    max_height_female: 24,
    max_weight_male: 100,
    max_weight_female: 80,
    min_height_male: 20,
    min_height_female: 20,
    min_weight_male: 75,
    min_weight_female: 60,
    grooming: 0,
    drooling: 0,
    good_with_strangers: 0,
    playfulness: 0,
    protectiveness: 0,
    energy: 1,
    name: "American Bulldog",
  },
  {
    id: 9,
    image_link: "https://api-ninjas.com/images/dogs/dalmatian.jpg",
    good_with_children: 3,
    good_with_other_dogs: 3,
    shedding: 4,
    grooming: 2,
    drooling: 2,
    coat_length: 1,
    good_with_strangers: 4,
    playfulness: 4,
    protectiveness: 4,
    trainability: 4,
    energy: 4,
    barking: 3,
    min_life_expectancy: 11,
    max_life_expectancy: 13,
    max_height_male: 24,
    max_height_female: 24,
    max_weight_male: 70,
    max_weight_female: 70,
    min_height_male: 19,
    min_height_female: 19,
    min_weight_male: 45,
    min_weight_female: 45,
    name: "Dalmatian",
  },
  {
    id: 10,
    image_link: "https://api-ninjas.com/images/dogs/pug.jpg",
    good_with_children: 5,
    good_with_other_dogs: 4,
    shedding: 4,
    grooming: 2,
    drooling: 1,
    coat_length: 1,
    good_with_strangers: 5,
    playfulness: 5,
    protectiveness: 3,
    trainability: 4,
    energy: 3,
    barking: 1,
    min_life_expectancy: 13,
    max_life_expectancy: 15,
    max_height_male: 13,
    max_height_female: 13,
    max_weight_male: 18,
    max_weight_female: 18,
    min_height_male: 10,
    min_height_female: 10,
    min_weight_male: 14,
    min_weight_female: 14,
    name: "Pug",
  },
  {
    id: 11,
    image_link: "https://api-ninjas.com/images/dogs/maltese.jpg",
    good_with_children: 3,
    good_with_other_dogs: 3,
    shedding: 1,
    grooming: 4,
    drooling: 1,
    coat_length: 1,
    good_with_strangers: 3,
    playfulness: 3,
    protectiveness: 4,
    trainability: 3,
    energy: 3,
    barking: 3,
    min_life_expectancy: 12,
    max_life_expectancy: 15,
    max_height_male: 9,
    max_height_female: 9,
    max_weight_male: 8.8,
    max_weight_female: 8.8,
    min_height_male: 7,
    min_height_female: 7,
    min_weight_male: 6.6,
    min_weight_female: 6.6,
    name: "Maltese",
  },
  {
    id: 12,
    image_link: "https://api-ninjas.com/images/dogs/poodle_(standard).jpg",
    good_with_children: 5,
    good_with_other_dogs: 3,
    shedding: 1,
    grooming: 4,
    drooling: 1,
    coat_length: 1,
    good_with_strangers: 5,
    playfulness: 5,
    protectiveness: 5,
    trainability: 5,
    energy: 4,
    barking: 4,
    min_life_expectancy: 10,
    max_life_expectancy: 18,
    max_height_male: 17,
    max_height_female: 17,
    max_weight_male: 70,
    max_weight_female: 50,
    min_height_male: 15,
    min_height_female: 15,
    min_weight_male: 60,
    min_weight_female: 40,
    name: "Poodle",
  },
];

export type Dogs = typeof dogsDatabase;
